version: '3'

services:
  app:
    container_name: logger
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - mongodb

  mongodb:
    container_name: logger-mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
